### ISSUE TITLE
Library @bobbymannino/svelte-progress no longer exists

### ISSUE THREAD

**Issue by kristianmandrup** [edwardspresume/sveltekit-lucia-auth-v3-example#6]
ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@bobbymannino/svelte-progress/-/svelte-progress-2.3.0.tgz: Not Found - 404

Not available on npmjs. I tried looking at his github, but not there either. Please replace with another working library ;)
What exactly is it intended to do?

**Comment by edwardspresume** [comment]
Oh I see, I guess it was removed. It was just supposed to show a progress bar at the top of the page when navigating to pages. I'll remove it from the branches
