### ISSUE TITLE
Passkeys and Svelte 5 runes support

### ISSUE THREAD

**Issue by kristianmandrup** [edwardspresume/sveltekit-lucia-auth-v3-example#7]
Lucia also supports passkeys as per: https://lucia-auth.com/guides/passkeys

There is a guide for how to use passkeys here: https://github.com/passlock-dev/ts-clients?tab=readme-ov-file#usage
which links to this sample app: https://github.com/passlock-dev/ts-clients/tree/master/apps/sveltekit and https://github.com/passlock-dev/ts-clients/tree/master/packages/sveltekit

See also: https://docs.passlock.dev/ and demonstrated here: https://d1rl0ue18b0151.cloudfront.net/?ref=madewithsvelte.com#

Would also be awesome if there was a branch with svelte upgraded to v5 RC using runes. The `$props` rune for page data should be easy for starters.

**Comment by edwardspresume** [comment]
Ok thank you for letting me know. I am still using lucia atm so when i have more time, i might make an update to this repo that covers passkeys and svelte 5
